import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#B6AAFE" },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    marginBottom: 4,
  },
  closeBtn: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  closeBtnText: {
    fontFamily: "Play_700Bold",
    fontSize: 28,
    lineHeight: 30,
  },
  flex: { flex: 1 },
  scroll: { padding: 20, paddingBottom: 40, gap: 12 },
  title: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 28,
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#3D1B77",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
    marginBottom: 4,
  },
  mealRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 4,
  },
  mealPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#3D1B77",
    backgroundColor: "#FFFFFF",
  },
  mealPillActive: {
    backgroundColor: "#3D1B77",
  },
  mealPillText: {
    fontFamily: "Play_700Bold",
    color: "#3D1B77",
    fontSize: 14,
  },
  mealPillTextActive: {
    color: "#FFFFFF",
  },
  field: { marginBottom: 4 },
  label: {
    fontFamily: "Play_700Bold",
    fontSize: 14,
    color: "#3D1B77",
    marginBottom: 4,
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#3D1B77",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontFamily: "Play_400Regular",
    fontSize: 16,
    color: "#3D1B77",
  },
  macroRow: { flexDirection: "row", gap: 8 },
  suggestionBox: {
    marginTop: 6,
    borderWidth: 2,
    borderRadius: 10,
    overflow: "hidden",
  },
  suggestionRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  suggestionName: {
    fontFamily: "Play_700Bold",
    fontSize: 15,
  },
  suggestionMeta: {
    fontFamily: "Play_400Regular",
    fontSize: 12,
    marginTop: 2,
  },
  addBtn: {
    backgroundColor: "#3D1B77",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  addBtnDisabled: { opacity: 0.5 },
  addBtnPressed: { opacity: 0.85 },
  addBtnText: {
    fontFamily: "PixelifySans_400Regular",
    color: "#FFFFFF",
    fontSize: 18,
  },
  sectionTitle: {
    fontFamily: "Play_700Bold",
    fontSize: 22,
    color: "#FFFFFF",
    marginTop: 12,
    textShadowColor: "#3D1B77",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  emptyText: {
    fontFamily: "Play_400Regular",
    color: "#3D1B77",
    fontSize: 14,
  },
  entryRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 12,
    borderWidth: 2,
    borderColor: "#3D1B77",
    gap: 10,
  },
  entryName: {
    fontFamily: "Play_700Bold",
    fontSize: 16,
    color: "#3D1B77",
  },
  entryMeta: {
    fontFamily: "Play_400Regular",
    fontSize: 12,
    color: "#3D1B77",
    marginTop: 2,
  },
  removeBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#B84A42",
  },
  removeBtnText: {
    fontFamily: "Play_700Bold",
    color: "#B84A42",
    fontSize: 12,
  },
  doneBtn: {
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#3D1B77",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 16,
  },
  doneBtnText: {
    fontFamily: "PixelifySans_400Regular",
    color: "#3D1B77",
    fontSize: 16,
  },
});
