import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#B6AAFE",
  },
  scroll: {
    padding: 16,
    paddingBottom: 40,
  },
  title: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 32,
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#3D1B77",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
    marginTop: 8,
    marginBottom: 16,
  },
  monthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  monthArrow: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#3D1B77",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  monthArrowText: {
    fontFamily: "Play_700Bold",
    fontSize: 20,
    color: "#3D1B77",
  },
  monthLabel: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 22,
    color: "#FFFFFF",
    textShadowColor: "#3D1B77",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  cardWrap: {
    position: "relative",
    marginBottom: 12,
  },
  cardShadow: {
    position: "absolute",
    top: 4,
    left: 2,
    right: 0,
    bottom: 0,
    backgroundColor: "#3D1B77",
    borderRadius: 18,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 12,
    borderWidth: 2,
    borderColor: "#3D1B77",
    marginRight: 2,
    marginBottom: 4,
  },
  weekHeader: {
    flexDirection: "row",
    marginBottom: 6,
  },
  weekHeaderCell: {
    flex: 1,
    alignItems: "center",
  },
  weekHeaderText: {
    fontFamily: "Play_700Bold",
    fontSize: 12,
    color: "#3D1B77",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  cell: {
    width: "14.285714%",
    aspectRatio: 1,
    padding: 3,
  },
  cellInner: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  cellToday: {
    borderWidth: 3,
  },
  cellEmpty: {
    backgroundColor: "transparent",
    borderColor: "transparent",
  },
  cellDay: {
    fontFamily: "Play_700Bold",
    fontSize: 14,
  },
  detailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 14,
    borderWidth: 2,
    borderColor: "#3D1B77",
    gap: 10,
    marginRight: 2,
    marginBottom: 4,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  detailTitle: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 20,
    color: "#3D1B77",
  },
  detailClose: {
    fontFamily: "Play_700Bold",
    fontSize: 24,
    color: "#3D1B77",
    paddingHorizontal: 6,
  },
  detailTotalsRow: {
    flexDirection: "row",
    gap: 6,
  },
  detailStat: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#3D1B77",
    backgroundColor: "#F3EFFF",
  },
  detailStatValue: {
    fontFamily: "Play_700Bold",
    fontSize: 20,
    color: "#3D1B77",
  },
  detailStatSuffix: {
    fontFamily: "Play_400Regular",
    fontSize: 11,
    color: "#3D1B77",
    marginTop: -2,
  },
  detailStatLabel: {
    fontFamily: "Play_400Regular",
    fontSize: 11,
    color: "#3D1B77",
    marginTop: 2,
  },
  detailMeals: {
    gap: 4,
  },
  detailMealRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE9FF",
  },
  detailMealName: {
    fontFamily: "Play_700Bold",
    fontSize: 14,
    color: "#3D1B77",
  },
  detailMealCals: {
    fontFamily: "Play_400Regular",
    fontSize: 14,
    color: "#3D1B77",
  },
  detailEditBtn: {
    backgroundColor: "#3D1B77",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 4,
  },
  detailEditBtnText: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 16,
    color: "#FFFFFF",
  },
  legendCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 12,
    borderWidth: 2,
    borderColor: "#3D1B77",
    gap: 6,
    marginRight: 2,
    marginBottom: 4,
  },
  legendTitle: {
    fontFamily: "Play_700Bold",
    fontSize: 14,
    color: "#3D1B77",
    marginBottom: 4,
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  legendSwatch: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#3D1B77",
  },
  legendText: {
    fontFamily: "Play_400Regular",
    fontSize: 13,
    color: "#3D1B77",
  },
  empty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 16,
  },
  emptyText: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 22,
    color: "#FFFFFF",
  },
});
