import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#B6AAFE",
  },
  scroll: {
    padding: 16,
    paddingBottom: 40,
  },
  title: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 32,
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#3D1B77",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
    marginTop: 8,
    marginBottom: 16,
  },
  daysRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  dayCell: {
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderRadius: 8,
    minWidth: 40,
  },
  dayCellSelected: {
    backgroundColor: "#E7E0FF",
    borderWidth: 2,
    borderColor: "#3D1B77",
  },
  dayLabel: {
    fontFamily: "Play_700Bold",
    fontSize: 13,
    color: "#3D1B77",
  },
  dayDate: {
    fontFamily: "Play_400Regular",
    fontSize: 14,
    color: "#3D1B77",
    marginTop: 2,
  },
  daySelectedText: {
    color: "#3D1B77",
  },
  cardWrap: {
    position: "relative",
    marginBottom: 16,
  },
  cardShadow: {
    position: "absolute",
    top: 4,
    left: 2,
    right: 0,
    bottom: 0,
    backgroundColor: "#3D1B77",
    borderRadius: 18,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
    borderWidth: 2,
    borderColor: "#3D1B77",
    marginRight: 2,
    marginBottom: 4,
  },
  calorieHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  mascot: {
    width: 54,
    height: 54,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#3D1B77",
    marginRight: 10,
  },
  mascotPlaceholder: {
    backgroundColor: "#FFD1D1",
    alignItems: "center",
    justifyContent: "center",
  },
  mascotInitial: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 28,
    color: "#B84A42",
  },
  consumedNumber: {
    fontFamily: "Play_700Bold",
    fontSize: 44,
    color: "#4FA064",
    marginRight: 8,
    textShadowColor: "#3D1B77",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  consumedLabelWrap: {
    flex: 1,
  },
  consumedLabel: {
    fontFamily: "Play_700Bold",
    fontSize: 16,
    color: "#3D1B77",
    lineHeight: 18,
  },
  targetWrap: {
    position: "relative",
  },
  targetShadow: {
    position: "absolute",
    top: 3,
    left: 3,
    right: 0,
    bottom: 0,
    backgroundColor: "#3D1B77",
    borderRadius: 8,
  },
  targetBox: {
    marginRight: 3,
    marginBottom: 3,
    borderWidth: 2,
    borderColor: "#3D1B77",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: "#FFFFFF",
  },
  targetText: {
    fontFamily: "Play_400Regular",
    fontSize: 14,
    color: "#3D1B77",
  },
  progressTrack: {
    height: 18,
    borderRadius: 10,
    backgroundColor: "#E7E0FF",
    borderWidth: 2,
    borderColor: "#3D1B77",
    overflow: "hidden",
    marginBottom: 14,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#4FA064",
  },
  macrosRow: {
    flexDirection: "row",
    gap: 8,
  },
  macroWrap: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    position: "relative",
  },
  macroShadow: {
    position: "absolute",
    top: 3,
    left: 3,
    right: 0,
    bottom: 0,
    borderRadius: 10,
  },
  macroBox: {
    marginRight: 3,
    marginBottom: 3,
    borderWidth: 2,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  macroValue: {
    fontFamily: "Play_700Bold",
    fontSize: 34,
    textAlign: "center",
    textShadowColor: "#3D1B77",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  macroLabel: {
    fontFamily: "Play_400Regular",
    fontSize: 11,
    marginTop: 2,
    textAlign: "center",
  },
  mealsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 12,
    borderWidth: 2,
    borderColor: "#3D1B77",
    marginRight: 2,
    marginBottom: 4,
    gap: 10,
  },
  mealRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderRadius: 12,
    padding: 8,
    gap: 12,
  },
  mealIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  mealImage: {
    width: 44,
    height: 44,
  },
  mealIconText: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 22,
    color: "#FFFFFF",
  },
  mealName: {
    fontFamily: "Play_400Regular",
    fontWeight: "700",
    fontSize: 18,
    flex: 1,
  },
  mealCalBox: {
    borderWidth: 2,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mealCalText: {
    fontFamily: "Play_400Regular",
    fontWeight: "700",
    fontSize: 15,
    color: "#FFFFFF",
  },
  waterCard: {
    backgroundColor: "#E7E0FF",
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: "#3D1B77",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  waterLabel: {
    fontFamily: "Play_400Regular",
    fontSize: 22,
    color: "#3D1B77",
  },
  waterDrops: {
    flexDirection: "row",
    gap: 10,
  },
  waterPress: {
    padding: 2,
  },
  waterImage: {
    width: 28,
    height: 32,
  },
  empty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 16,
  },
  emptyText: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 22,
    color: "#FFFFFF",
  },
  cta: {
    backgroundColor: "#3D1B77",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 40,
  },
  ctaText: {
    fontFamily: "PixelifySans_400Regular",
    fontSize: 18,
    color: "#FFFFFF",
  },
});
